train:
  num_workers: 16
  batch_size: 64
  adam:
    lr: 0.0003
    weight_decay: 0.000001
  mask_padding: True
  decay:
    rate: 0.05
    start: 25000
    end: 50000
  grad_clip: 1.0  # 0 for no gradient clipping
  max_epochs: 10000
  teacher_force:
    rate: 0.5
###########################
log:
  ckpt_dir: 'ckpt/cota'
  log_dir: 'logs/cota'
